"""empty message

Revision ID: 73302c30da3f
Revises: 
Create Date: 2020-02-29 17:36:39.996266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73302c30da3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('cid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('cid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('portrait', sa.String(length=300), nullable=True),
    sa.Column('regtime', sa.DateTime(), nullable=True),
    sa.Column('isforbid', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('article',
    sa.Column('aid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('content', sa.String(length=10000), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('replies', sa.Integer(), nullable=True),
    sa.Column('picture', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['category.cid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('aid')
    )
    op.create_table('mark',
    sa.Column('mid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('mid')
    )
    op.create_table('tag',
    sa.Column('tid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('aid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aid'], ['article.aid'], ),
    sa.PrimaryKeyConstraint('tid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    op.drop_table('mark')
    op.drop_table('article')
    op.drop_table('user')
    op.drop_table('category')
    # ### end Alembic commands ###
